steps:
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-central1-docker.pkg.dev/test-397216/clients-mongo/banquito:latest", "."]
  - name: gcr.io/cloud-builders/docker
    args: [ "push", "us-central1-docker.pkg.dev/test-397216/clients-mongo/banquito:latest"]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'us-central1-docker.pkg.dev/test-397216/clients-mongo/banquito:latest'
      - '-- port 8761'
      - '--region'
      - 'us-central1'
images:
  - "us-central1-docker.pkg.dev/test-397216/clients-mongo/banquito:latest"